import { discoveryQuestions } from '../data/questions'
import type { CalibrationPersona } from './calibrationTypes'
import {
  expectActivityStatus,
  expectBandAtLeast,
  expectBandAtMost,
  expectBlindSpot,
  expectConfidence,
  expectCriticalFlag,
  expectRawAboveRanking,
  expectReadinessBand,
  expectRoleAbove,
  expectRoleCountAtLeast,
  expectRoleCountAtMost,
  expectRoleInTop,
} from './expectations'

const broadAnswers = (answer: string, overrides: Record<string, string> = {}) => Object.fromEntries(
  discoveryQuestions.filter((question) => question.phase === 'broad').map((question) => [question.id, overrides[question.id] ?? answer]),
)

const allDiscoveryAnswers = (answer: string) => Object.fromEntries(discoveryQuestions.map((question) => [question.id, answer]))

export const calibrationPersonas: CalibrationPersona[] = [
  {
    id: 'caring-service-dominant',
    name: 'Caring service-oriented authority holder',
    description: 'Strongly enjoys directing, service, and caregiving, while expressing little interest in pain-giving.',
    traitIntent: { dominance: 'high', givingControl: 'high', serviceGiving: 'high', caregiving: 'high', painGiving: 'low' },
    discoveryAnswers: { 'd-power-give': 'strong', 'r-lead': 'strong', 'd-service': 'strong', 'r-service-direct': 'strong', 'r-service-give': 'strong', 'd-care': 'strong', 'r-care-give': 'strong', 'r-protector': 'some', 'd-intensity': 'no', 'r-pain-give': 'no' },
    expectedStrongRoles: ['service-dominant'],
    expectedPlausibleRoles: ['dominant', 'nurturing-dominant'],
    rolesNotExpectedHigh: ['sadist'],
    rationale: 'Care, service, and authority should coexist without importing sadistic interest.',
    expectations: [expectRoleInTop('service-dominant', 8), expectRoleAbove('service-dominant', 'sadist')],
  },
  {
    id: 'bidirectional-power',
    name: 'Bidirectional power interest',
    description: 'Strong interest in both directing and yielding, with explicit interest in changing sides.',
    traitIntent: { dominance: 'high', submission: 'high', switching: 'high', givingControl: 'high', receivingControl: 'high' },
    discoveryAnswers: { 'd-power-give': 'strong', 'd-power-receive': 'strong', 'd-flexibility': 'strong', 'r-both-power': 'strong', 'r-lead': 'some', 'r-surrender': 'some', 'r-positions': 'strong' },
    expectedStrongRoles: ['switch'],
    expectedPlausibleRoles: ['dominant', 'submissive'],
    rationale: 'Independent directional axes must not average one another away.',
    expectations: [expectRoleInTop('switch', 5)],
  },
  {
    id: 'rope-receiver',
    name: 'Rope receiver, not rope giver',
    description: 'Interested in being tied and restrained, with explicit disinterest in tying others.',
    traitIntent: { ropeReceiving: 'high', restraint: 'high', ropeGiving: 'low', technicalInterest: 'low' },
    discoveryAnswers: { 'd-rope': 'some', 'r-rope-receive': 'strong', 'r-rope-give': 'no', 'r-rope-both': 'no', 'd-position-receive': 'strong', 'r-bottom': 'strong' },
    expectedStrongRoles: ['rope-bottom'],
    rolesNotExpectedHigh: ['rigger'],
    rationale: 'Receiving rope is distinct from the technical craft of tying.',
    expectations: [expectRoleInTop('rope-bottom', 5), expectRoleAbove('rope-bottom', 'rigger')],
  },
  {
    id: 'technical-rope-giver',
    name: 'Technical rope giver without power exchange',
    description: 'Strong interest in tying and technical craft, but low interest in broad authority.',
    traitIntent: { ropeGiving: 'high', technicalInterest: 'high', dominance: 'low', givingControl: 'low' },
    discoveryAnswers: { 'd-rope': 'strong', 'r-rope-give': 'strong', 'r-rope-receive': 'no', 'r-rope-both': 'no', 'd-position-give': 'strong', 'r-top': 'strong', 'd-power-give': 'no', 'd-power-receive': 'no' },
    expectedStrongRoles: ['rigger'],
    rolesNotExpectedHigh: ['dominant'],
    rationale: 'Technical rope interest should not be treated as evidence of a Dominant identity.',
    expectations: [expectRoleInTop('rigger', 5), expectRoleAbove('rigger', 'dominant')],
  },
  {
    id: 'pain-receiver-independent',
    name: 'Pain receiver with low submission',
    description: 'Enjoys receiving intense sensation but does not want to yield authority.',
    traitIntent: { painReceiving: 'high', physicalIntensity: 'high', submission: 'low', receivingControl: 'low' },
    discoveryAnswers: { 'd-intensity': 'some', 'r-pain-receive': 'strong', 'r-pain-give': 'no', 'd-position-receive': 'strong', 'r-bottom': 'strong', 'd-power-receive': 'no', 'r-surrender': 'no' },
    expectedStrongRoles: ['masochist'],
    expectedPlausibleRoles: ['bottom'],
    rolesNotExpectedHigh: ['submissive'],
    rationale: 'Masochistic interest and submission are independent dimensions.',
    expectations: [expectRoleInTop('masochist', 5), expectRoleAbove('masochist', 'submissive')],
  },
  {
    id: 'caring-pain-giver',
    name: 'Caring pain giver',
    description: 'Strong pain-giving and caregiving interests expressed together.',
    traitIntent: { painGiving: 'high', caregiving: 'high', responsibility: 'high', emotionalConnection: 'moderate' },
    discoveryAnswers: { 'd-intensity': 'strong', 'r-pain-give': 'strong', 'd-care': 'strong', 'r-care-give': 'strong', 'r-protector': 'some', 'd-service': 'some' },
    expectedPlausibleRoles: ['sadist', 'caregiver'],
    rationale: 'Intensity and care can coexist without cancelling or stereotyping either interest.',
    expectations: [expectRoleInTop('sadist', 10), expectRoleInTop('caregiver', 12)],
  },
  {
    id: 'playful-brat-independent',
    name: 'Playful brat without submissive identity',
    description: 'Enjoys negotiated provocation but rejects yielding authority.',
    traitIntent: { brattiness: 'high', playfulness: 'high', challenge: 'high', submission: 'low' },
    discoveryAnswers: { 'd-brat': 'strong', 'r-brat': 'strong', 'r-tamer': 'no', 'd-power-receive': 'no', 'r-surrender': 'no', 'd-roleplay': 'some' },
    expectedStrongRoles: ['brat'],
    rolesNotExpectedHigh: ['submissive'],
    rationale: 'Brat vocabulary must not depend on submission.',
    expectations: [expectRoleInTop('brat', 5), expectRoleAbove('brat', 'submissive')],
  },
  {
    id: 'self-advocating-submissive',
    name: 'Self-advocating consent-literate submissive',
    description: 'Strong yielding interest paired with clear self-advocacy and consent knowledge.',
    traitIntent: { submission: 'high', receivingControl: 'high', surrender: 'high', responsibility: 'moderate' },
    discoveryAnswers: { 'd-power-receive': 'strong', 'r-surrender': 'strong', 'd-power-give': 'no', 'd-flexibility': 'no', 'r-both-power': 'no', 'd-structure': 'some', 'r-discipline-receive': 'some' },
    readinessIntent: ['Strong ongoing consent literacy', 'Strong self-advocacy'],
    readinessAnswers: { 'c-ongoing-1': 'a', 'c-ongoing-2': 'a', 'c-self-1': 'a', 'c-self-2': 'a', 'c-stop-1': 'a', 'c-neg-1': 'a' },
    expectedStrongRoles: ['submissive'],
    expectedReadinessObservations: ['Submission does not reduce agency or readiness.'],
    rationale: 'Role interest and self-advocacy must remain independent.',
    expectations: [expectRoleInTop('submissive', 5), expectReadinessBand('ongoingConsent', 'strong'), expectReadinessBand('selfAdvocacy', 'strong')],
  },
  {
    id: 'dominant-consent-gap',
    name: 'Dominant alignment with an ongoing-consent gap',
    description: 'Strong authority interest alongside a critical misconception about prior agreement.',
    traitIntent: { dominance: 'high', givingControl: 'high', leadership: 'high' },
    discoveryAnswers: { 'd-power-give': 'strong', 'r-lead': 'strong', 'd-power-receive': 'no', 'd-flexibility': 'no', 'r-both-power': 'no' },
    readinessIntent: ['Most readiness answers are strong', 'Prior negotiation misconception remains critical'],
    readinessAnswers: { 'c-ongoing-1': 'c', 'c-ongoing-2': 'a', 'c-neg-1': 'a', 'c-stop-1': 'a', 'c-account-1': 'a' },
    expectedStrongRoles: ['dominant'],
    expectedBlindSpots: ['prior-negotiation'],
    rationale: 'A readiness gap must remain visible without suppressing identity vocabulary.',
    expectations: [expectRoleInTop('dominant', 6), expectCriticalFlag('prior-negotiation'), expectReadinessBand('ongoingConsent', 'developing', 'explore', 'important')],
  },
  {
    id: 'rope-vocabulary-hard-limit',
    name: 'Rope vocabulary with a present hard limit',
    description: 'Historical or vocabulary-level rope alignment while rope is currently a hard boundary.',
    traitIntent: { ropeReceiving: 'high', restraint: 'high', ropeGiving: 'low' },
    discoveryAnswers: { 'd-rope': 'some', 'r-rope-receive': 'strong', 'r-rope-give': 'no', 'd-position-receive': 'strong', 'r-bottom': 'strong' },
    boundaryIntent: { rope: 'hard-limit' },
    expectedStrongRoles: ['rope-bottom'],
    rationale: 'A current activity boundary cannot rewrite vocabulary alignment.',
    expectations: [expectRoleInTop('rope-bottom', 5), expectActivityStatus('rope', 'off-table')],
  },
  {
    id: 'mostly-withheld',
    name: 'Mostly unsure or withheld',
    description: 'Uses uncertainty and prefer-not options across broad domains.',
    traitIntent: { dominance: 'unknown', submission: 'unknown', ropeGiving: 'unknown', caregiving: 'unknown' },
    discoveryAnswers: broadAnswers('prefer-not', { 'd-rope': 'unknown', 'd-intensity': 'unknown', 'd-care': 'prefer-not' }),
    expectedConfidence: { dominant: ['low'], rigger: ['low'], caregiver: ['low'] },
    rationale: 'Withheld answers provide no evidence and should produce limited conclusions.',
    expectations: [expectBandAtMost('dominant', 'insufficient'), expectBandAtMost('rigger', 'insufficient')],
  },
  {
    id: 'sparse-perfect-rope',
    name: 'One strong rope answer',
    description: 'Only one highly specific rope-craft answer is available.',
    traitIntent: { ropeGiving: 'high', technicalInterest: 'high' },
    discoveryAnswers: { 'r-rope-give': 'strong' },
    expectedStrongRoles: ['rigger'],
    expectedConfidence: { rigger: ['low'] },
    rationale: 'Raw alignment may be strong while ranking and confidence remain cautious.',
    expectations: [expectRawAboveRanking('rigger')],
  },
  {
    id: 'service-without-power',
    name: 'Service giver without power exchange',
    description: 'Values practical and caring service while rejecting both authority directions.',
    traitIntent: { serviceGiving: 'high', caregiving: 'moderate', dominance: 'low', submission: 'low' },
    discoveryAnswers: { 'd-service': 'strong', 'r-service-give': 'strong', 'r-service-direct': 'no', 'd-care': 'strong', 'r-care-give': 'some', 'd-power-give': 'no', 'd-power-receive': 'no' },
    expectedPlausibleRoles: ['domestic-service-giver'],
    rolesNotExpectedHigh: ['dominant', 'submissive'],
    rationale: 'Service is not inherently dominant or submissive.',
    expectations: [expectRoleInTop('domestic-service-giver', 8), expectRoleAbove('domestic-service-giver', 'service-dominant')],
  },
  {
    id: 'service-receiver-submissive',
    name: 'Submissive service receiver',
    description: 'Strongly values yielding and being thoughtfully attended to.',
    traitIntent: { serviceReceiving: 'high', submission: 'high', receivingControl: 'high', emotionalConnection: 'high' },
    discoveryAnswers: { 'r-service-receive': 'strong', 'd-power-receive': 'strong', 'r-surrender': 'strong', 'd-position-receive': 'some', 'r-bottom': 'some', 'd-care': 'some' },
    expectedPlausibleRoles: ['service-receiver', 'submissive'],
    rationale: 'Service receiving and submission can overlap while remaining distinguishable.',
    expectations: [expectRoleInTop('service-receiver', 10), expectRoleInTop('submissive', 10)],
  },
  {
    id: 'primal-low-protocol',
    name: 'Primal interest with low formal protocol',
    description: 'Strong embodied pursuit interest and spontaneity with little interest in ritual or formal structure.',
    traitIntent: { primality: 'high', spontaneity: 'high', givingControl: 'moderate', protocol: 'low', ritual: 'low' },
    discoveryAnswers: { 'd-primal': 'strong', 'r-primal-give': 'strong', 'r-primal-receive': 'no', 'd-structure': 'no', 'r-protocol': 'no', 'r-positions': 'some' },
    expectedStrongRoles: ['primal-hunter'],
    rolesNotExpectedHigh: ['protocol-enthusiast'],
    rationale: 'Primal spontaneity should not inflate protocol vocabulary.',
    expectations: [expectRoleInTop('primal-hunter', 6), expectRoleAbove('primal-hunter', 'ritual-dominant')],
  },
  {
    id: 'structured-protocol',
    name: 'Structured ritual and protocol interest',
    description: 'Strong interest in protocol, ritual, and structure with only moderate power-exchange signals.',
    traitIntent: { protocol: 'high', ritual: 'high', structure: 'high', dominance: 'moderate', submission: 'moderate' },
    discoveryAnswers: { 'd-structure': 'curious', 'r-protocol': 'strong', 'd-lifestyle': 'some', 'r-lifestyle-ritual': 'strong', 'd-power-give': 'curious', 'd-power-receive': 'curious' },
    expectedStrongRoles: ['protocol-enthusiast'],
    expectedPlausibleRoles: ['ongoing-protocol-partner'],
    rationale: 'Formal structure should lead the result rather than a generic power position.',
    expectations: [expectRoleInTop('protocol-enthusiast', 5)],
  },
  {
    id: 'exhibition-without-power',
    name: 'Exhibition interest without power exchange',
    description: 'Enjoys being watched or displayed without wanting to direct or yield authority.',
    traitIntent: { exhibitionism: 'high', performance: 'high', dominance: 'low', submission: 'low' },
    discoveryAnswers: { 'd-visibility': 'strong', 'r-exhibit': 'strong', 'r-voyeur': 'no', 'd-power-give': 'no', 'd-power-receive': 'no', 'd-roleplay': 'some' },
    expectedStrongRoles: ['exhibitionist'],
    rolesNotExpectedHigh: ['dominant'],
    rationale: 'Visibility preferences should not infer a power identity.',
    expectations: [expectRoleInTop('exhibitionist', 5), expectRoleAbove('exhibitionist', 'dominant')],
  },
  {
    id: 'observer-low-participation',
    name: 'Observer with low participation drive',
    description: 'Strongly prefers consensual observation and rejects being displayed or taking an active position.',
    traitIntent: { voyeurism: 'high', exhibitionism: 'low', performance: 'low', leadership: 'low' },
    discoveryAnswers: { 'd-visibility': 'some', 'r-voyeur': 'strong', 'r-exhibit': 'no', 'd-position-give': 'no', 'd-position-receive': 'no' },
    expectedStrongRoles: ['voyeur'],
    rolesNotExpectedHigh: ['exhibitionist'],
    rationale: 'Observer vocabulary should separate from performance and exhibition.',
    expectations: [expectRoleInTop('voyeur', 5), expectRoleAbove('voyeur', 'exhibitionist')],
  },
  {
    id: 'scene-roleplayer',
    name: 'Fantasy roleplayer without lifestyle orientation',
    description: 'Strong imaginative and character interest while rejecting an ongoing lifestyle structure.',
    traitIntent: { roleplay: 'high', exploration: 'high', lifestyleOrientation: 'low' },
    discoveryAnswers: { 'd-roleplay': 'strong', 'r-story-enter': 'strong', 'r-story-lead': 'some', 'd-lifestyle': 'no', 'r-lifestyle-power': 'no', 'r-lifestyle-ritual': 'no', 'd-exploration': 'some' },
    expectedPlausibleRoles: ['immersive-roleplayer', 'character-player'],
    rolesNotExpectedHigh: ['lifestyle-dominant', 'lifestyle-submissive'],
    rationale: 'Fantasy interests do not imply an ongoing authority structure.',
    expectations: [expectRoleInTop('immersive-roleplayer', 8), expectRoleAbove('immersive-roleplayer', 'lifestyle-dominant')],
  },
  {
    id: 'broad-explorer',
    name: 'Broad, moderate explorer',
    description: 'Curious across several unrelated areas without a single settled role direction.',
    traitIntent: { exploration: 'high', communityConnection: 'moderate', roleplay: 'moderate', sensorySeeking: 'moderate', switching: 'moderate' },
    discoveryAnswers: { 'd-exploration': 'strong', 'd-community': 'some', 'd-roleplay': 'curious', 'd-material': 'curious', 'd-care': 'curious', 'd-intensity': 'curious', 'd-flexibility': 'curious', 'r-community': 'some', 'r-positions': 'curious', 'r-sensation': 'curious' },
    expectedPlausibleRoles: ['kink-explorer'],
    expectedConfidence: { 'kink-explorer': ['moderate', 'high'] },
    rationale: 'Breadth should produce several plausible options rather than one artificial winner.',
    expectations: [expectRoleInTop('kink-explorer', 8), expectRoleCountAtLeast('explore', 3)],
  },
  {
    id: 'all-high-adversarial',
    name: 'Adversarial all-high profile',
    description: 'Marks every scored question strongly to test saturation and result stability.',
    traitIntent: { dominance: 'conflicting', submission: 'conflicting', switching: 'high', exploration: 'high' },
    discoveryAnswers: allDiscoveryAnswers('strong'),
    expectedConfidence: { switch: ['high'], 'kink-explorer': ['high'] },
    rationale: 'The engine should remain finite and evidence-aware under an unrealistic saturated profile.',
    expectations: [expectRoleCountAtLeast('strong', 5), expectBandAtLeast('switch', 'strong')],
  },
  {
    id: 'all-low-adversarial',
    name: 'Adversarial all-low profile',
    description: 'Rejects every scored discovery question.',
    traitIntent: { dominance: 'low', submission: 'low', ropeGiving: 'low', ropeReceiving: 'low', exploration: 'low' },
    discoveryAnswers: allDiscoveryAnswers('no'),
    rolesNotExpectedHigh: ['dominant', 'submissive', 'rigger', 'rope-bottom', 'sadist', 'masochist'],
    rationale: 'Negative evidence must not manufacture strong alignment.',
    expectations: [expectRoleCountAtMost('strong', 0)],
  },
  {
    id: 'safeword-misconception-amid-strengths',
    name: 'Safeword misconception amid strong readiness',
    description: 'Strong answers across readiness domains plus one critical belief that safeword use is the only stop signal.',
    traitIntent: {},
    discoveryAnswers: { 'd-exploration': 'some' },
    readinessIntent: ['Broadly strong readiness', 'Safeword-only misconception must persist'],
    readinessAnswers: { 'c-stop-1': 'c', 'c-stop-2': 'a', 'c-ongoing-1': 'a', 'c-ongoing-2': 'a', 'c-neg-1': 'a', 'c-comm-1': 'a', 'c-bound-1': 'a', 'c-risk-1': 'a' },
    expectedBlindSpots: ['safeword-only'],
    rationale: 'A critical misconception cannot disappear into a strong average.',
    expectations: [expectCriticalFlag('safeword-only'), expectReadinessBand('stopSignals', 'developing', 'explore', 'important')],
  },
  {
    id: 'multiple-hard-limits',
    name: 'Multiple boundaries with exploratory vocabulary',
    description: 'Curious vocabulary signals coexist with hard limits, uncertainty, and a withheld boundary answer.',
    traitIntent: { ropeReceiving: 'moderate', painReceiving: 'moderate', roleplay: 'moderate' },
    discoveryAnswers: { 'd-rope': 'some', 'r-rope-receive': 'some', 'd-intensity': 'some', 'r-pain-receive': 'some', 'd-roleplay': 'some' },
    boundaryIntent: { rope: 'hard-limit', impact: 'dont-want', sensation: 'unknown', roleplay: 'prefer-not' },
    rationale: 'Each boundary value affects activity guidance only and retains its distinct meaning.',
    expectations: [expectActivityStatus('rope', 'off-table'), expectActivityStatus('impact', 'off-table'), expectActivityStatus('sensation', 'learn-first'), expectRoleAbove('rope-bottom', 'rigger')],
  },
  {
    id: 'contradictory-clusters',
    name: 'Contradictory directional clusters',
    description: 'Broad answers and refinements disagree about switching, rope direction, and power direction.',
    traitIntent: { switching: 'conflicting', ropeGiving: 'conflicting', ropeReceiving: 'conflicting', dominance: 'conflicting', submission: 'conflicting' },
    discoveryAnswers: { 'd-power-give': 'strong', 'd-power-receive': 'strong', 'd-flexibility': 'no', 'r-both-power': 'strong', 'd-rope': 'strong', 'r-rope-give': 'no', 'r-rope-receive': 'strong', 'r-rope-both': 'strong' },
    expectedConfidence: { switch: ['moderate', 'high'], 'bondage-switch': ['moderate', 'high'] },
    rationale: 'Conflicting evidence should remain visible as mixed scores rather than collapse to zero or certainty.',
    expectations: [expectBandAtLeast('switch', 'explore'), expectBandAtLeast('bondage-switch', 'explore')],
  },
  {
    id: 'niche-objectification-frame',
    name: 'Niche objectification roleplay interest',
    description: 'Strong, specifically bounded interest in objectification symbolism and roleplay without relying on generic material interest.',
    traitIntent: { objectification: 'high', roleplay: 'high', psychologicalIntensity: 'moderate', fetishInterest: 'moderate' },
    discoveryAnswers: { 'r-objectification-frame': 'strong', 'r-objectification-focus': 'strong', 'd-roleplay': 'strong', 'r-story-enter': 'some', 'd-material': 'curious' },
    expectedStrongRoles: ['objectification-player'],
    expectedConfidence: { 'objectification-player': ['moderate', 'high'] },
    rationale: 'A niche role-defining trait must be reachable and distinguishable through more than one answer path.',
    expectations: [expectRoleInTop('objectification-player', 5)],
  },
  {
    id: 'service-top-without-authority',
    name: 'Active service without authority',
    description: 'Enjoys providing service as an active position while rejecting broader authority.',
    traitIntent: { serviceGiving: 'high', leadership: 'high', pleasureGiving: 'high', dominance: 'low' },
    discoveryAnswers: { 'd-service': 'strong', 'r-service-give': 'strong', 'r-service-position': 'strong', 'd-position-give': 'strong', 'r-top': 'strong', 'd-power-give': 'no' },
    expectedStrongRoles: ['service-top'],
    rolesNotExpectedHigh: ['dominant'],
    rationale: 'An active service position must remain distinct from negotiated authority.',
    expectations: [expectRoleInTop('service-top', 5), expectRoleAbove('service-top', 'service-dominant'), expectRoleAbove('service-top', 'dominant')],
  },
  {
    id: 'service-bottom-without-submission',
    name: 'Receiving service without submission',
    description: 'Enjoys being the focus of service while rejecting a submissive role.',
    traitIntent: { serviceReceiving: 'high', pleasureReceiving: 'high', submission: 'low' },
    discoveryAnswers: { 'r-service-receive': 'strong', 'r-service-receive-position': 'strong', 'd-position-receive': 'strong', 'r-bottom': 'strong', 'd-power-receive': 'no' },
    expectedStrongRoles: ['service-bottom'],
    rolesNotExpectedHigh: ['submissive'],
    rationale: 'Receiving service as an activity focus does not imply submission or authority.',
    expectations: [expectRoleInTop('service-bottom', 5), expectRoleAbove('service-bottom', 'service-receiver'), expectRoleAbove('service-bottom', 'submissive')],
  },
  {
    id: 'praise-giver-without-dominance',
    name: 'Praise giver without dominance',
    description: 'Values giving warm, specific recognition without wanting authority.',
    traitIntent: { pleasureGiving: 'high', emotionalConnection: 'high', dominance: 'low' },
    discoveryAnswers: { 'r-praise-direction': 'strong', 'r-praise-context': 'strong', 'd-position-give': 'some', 'd-power-give': 'no', 'd-psych': 'some' },
    expectedStrongRoles: ['praise-giver'],
    rolesNotExpectedHigh: ['dominant'],
    rationale: 'Giving praise can be relationally meaningful without being an authority signal.',
    expectations: [expectRoleInTop('praise-giver', 6), expectRoleAbove('praise-giver', 'praise-focused-player'), expectRoleAbove('praise-giver', 'dominant')],
  },
  {
    id: 'praise-receiver-without-submission',
    name: 'Praise receiver without submission',
    description: 'Values receiving recognition and warmth without wanting a submissive role.',
    traitIntent: { pleasureReceiving: 'high', emotionalConnection: 'high', submission: 'low' },
    discoveryAnswers: { 'r-praise-direction': 'some', 'r-praise-context': 'strong', 'd-position-receive': 'some', 'd-power-receive': 'no', 'd-psych': 'some' },
    expectedStrongRoles: ['praise-focused-player'],
    rolesNotExpectedHigh: ['submissive'],
    rationale: 'Receiving praise is not evidence of submission.',
    expectations: [expectRoleInTop('praise-focused-player', 6), expectRoleAbove('praise-focused-player', 'praise-giver'), expectRoleAbove('praise-focused-player', 'submissive')],
  },
  {
    id: 'objectifier-without-sadism',
    name: 'Objectification giver without sadism',
    description: 'Interested in creating a bounded objectification frame while rejecting pain-giving.',
    traitIntent: { objectification: 'high', givingControl: 'moderate', roleplay: 'high', painGiving: 'low' },
    discoveryAnswers: { 'r-objectification-direction': 'strong', 'r-objectification-frame': 'strong', 'r-objectification-focus': 'strong', 'd-roleplay': 'strong', 'd-intensity': 'no', 'r-pain-give': 'no' },
    expectedStrongRoles: ['objectifier'],
    rolesNotExpectedHigh: ['sadist'],
    rationale: 'Objectification direction must not import pain interest or actual entitlement.',
    expectations: [expectRoleInTop('objectifier', 6), expectRoleAbove('objectifier', 'objectified-roleplayer'), expectRoleAbove('objectifier', 'sadist')],
  },
  {
    id: 'objectified-without-submission',
    name: 'Objectified role without submission',
    description: 'Interested in entering a bounded fictional frame while rejecting broader submission.',
    traitIntent: { objectification: 'high', receivingControl: 'moderate', roleplay: 'high', submission: 'low' },
    discoveryAnswers: { 'r-objectification-direction': 'some', 'r-objectification-frame': 'strong', 'r-objectification-focus': 'strong', 'd-roleplay': 'strong', 'd-power-receive': 'no' },
    expectedStrongRoles: ['objectified-roleplayer'],
    rolesNotExpectedHigh: ['submissive'],
    rationale: 'An objectified roleplay position does not imply submission or loss of agency.',
    expectations: [expectRoleInTop('objectified-roleplayer', 6), expectRoleAbove('objectified-roleplayer', 'objectifier'), expectRoleAbove('objectified-roleplayer', 'submissive')],
  },
  {
    id: 'objectification-direction-switch',
    name: 'Mixed objectification directions',
    description: 'Interested in changing positions or co-creating objectification framing.',
    traitIntent: { objectification: 'high', switching: 'high', roleplay: 'high' },
    discoveryAnswers: { 'r-objectification-direction': 'curious', 'r-objectification-frame': 'strong', 'r-objectification-focus': 'strong', 'd-roleplay': 'strong', 'd-flexibility': 'strong' },
    expectedStrongRoles: ['objectification-player'],
    rationale: 'Mixed directional evidence should support the flexible canonical role rather than both directional variants dominating.',
    expectations: [expectRoleInTop('objectification-player', 6), expectRoleAbove('objectification-player', 'objectifier'), expectRoleAbove('objectification-player', 'objectified-roleplayer')],
  },
  {
    id: 'directional-evidence-uncertain',
    name: 'Uncertain about new directional evidence',
    description: 'Withholds or remains unsure about service, praise, and objectification direction.',
    traitIntent: { serviceGiving: 'unknown', serviceReceiving: 'unknown', objectification: 'unknown' },
    discoveryAnswers: { 'r-service-position': 'unknown', 'r-service-receive-position': 'prefer-not', 'r-praise-direction': 'unknown', 'r-praise-context': 'prefer-not', 'r-objectification-direction': 'unknown' },
    expectedConfidence: { 'service-top': ['low'], 'service-bottom': ['low'], 'praise-giver': ['low'], objectifier: ['low'] },
    rationale: 'Uncertainty and withheld answers must remain no-score rather than manufacturing a directional result.',
    expectations: [expectBandAtMost('service-top', 'insufficient'), expectBandAtMost('praise-giver', 'insufficient'), expectBandAtMost('objectifier', 'insufficient')],
  },
  {
    id: 'strong-readiness-low-alignment',
    name: 'Strong readiness with low role alignment',
    description: 'Demonstrates strong consent, communication, boundary, and risk knowledge while rejecting the sampled role interests.',
    traitIntent: { dominance: 'low', submission: 'low', exploration: 'low' },
    discoveryAnswers: broadAnswers('no'),
    readinessIntent: ['Strong knowledge and attitudes do not create role alignment or certify safety.'],
    readinessAnswers: { 'c-ongoing-1': 'a', 'c-neg-1': 'a', 'c-comm-1': 'a', 'c-bound-1': 'a', 'c-self-1': 'a', 'c-risk-1': 'a', 'c-stop-1': 'a' },
    expectedReadinessObservations: ['Strong readiness remains separate from low discovery alignment.'],
    rationale: 'Knowledge must neither manufacture identity vocabulary nor be presented as a safety certification.',
    expectations: [expectRoleCountAtMost('strong', 0), expectReadinessBand('ongoingConsent', 'strong'), expectReadinessBand('boundaries', 'strong')],
  },
  {
    id: 'rope-direction-switch',
    name: 'Rope giver and receiver with explicit flexibility',
    description: 'Strongly values both tying and being tied and explicitly wants both directions.',
    traitIntent: { ropeGiving: 'high', ropeReceiving: 'high', switching: 'high', technicalInterest: 'high' },
    discoveryAnswers: { 'd-rope': 'strong', 'r-rope-give': 'strong', 'r-rope-receive': 'strong', 'r-rope-both': 'strong', 'd-flexibility': 'strong', 'r-both-power': 'some' },
    expectedStrongRoles: ['bondage-switch'],
    rationale: 'Bidirectional rope evidence should distinguish Rope Switch vocabulary from one-direction rope roles.',
    expectations: [expectRoleInTop('bondage-switch', 5), expectRoleAbove('bondage-switch', 'rigger'), expectRoleAbove('bondage-switch', 'rope-bottom')],
  },
  {
    id: 'gentle-authority-without-intensity',
    name: 'Warm authority without pain interest',
    description: 'Values negotiated direction, care, and reassurance while rejecting pain-giving.',
    traitIntent: { dominance: 'high', caregiving: 'high', emotionalConnection: 'high', painGiving: 'low' },
    discoveryAnswers: { 'd-power-give': 'strong', 'r-lead': 'strong', 'd-care': 'strong', 'r-care-give': 'strong', 'r-protector': 'strong', 'd-intensity': 'no', 'r-pain-give': 'no' },
    expectedStrongRoles: ['gentle-dominant'],
    rolesNotExpectedHigh: ['sadist'],
    rationale: 'Nearby dominant styles should use care evidence rather than generic dominance intensity.',
    expectations: [expectRoleInTop('gentle-dominant', 6), expectRoleAbove('gentle-dominant', 'sadist')],
  },
  {
    id: 'broad-and-service-authority',
    name: 'Broad authority with a service-focused refinement',
    description: 'Both broad authority and service-focused responsibility are strongly supported.',
    traitIntent: { dominance: 'high', serviceGiving: 'high', responsibility: 'high', pleasureGiving: 'high' },
    discoveryAnswers: { 'd-power-give': 'strong', 'r-lead': 'strong', 'r-authority-style': 'strong', 'd-service': 'strong', 'r-service-give': 'strong', 'r-service-direct': 'strong', 'r-service-position': 'curious' },
    expectedStrongRoles: ['dominant', 'service-dominant'],
    rationale: 'A niche style may refine a broad role without erasing the broader pattern.',
    expectations: [expectRoleInTop('dominant', 12), expectRoleInTop('service-dominant', 6)],
  },
  {
    id: 'sparse-broad-authority',
    name: 'Sparse broad authority evidence',
    description: 'Only one broad authority answer is available, so confidence must remain cautious.',
    traitIntent: { dominance: 'moderate', givingControl: 'moderate' },
    discoveryAnswers: { 'd-power-give': 'strong' },
    expectedConfidence: { dominant: ['low'] },
    rationale: 'A single broad answer can suggest a direction without justifying high confidence.',
    expectations: [expectConfidence('dominant', 'low'), expectRawAboveRanking('dominant')],
  },
  {
    id: 'multi-family-role-patterns',
    name: 'Several independently supported role families',
    description: 'Authority, rope craft, primal energy, and service all have independent positive evidence.',
    traitIntent: { dominance: 'high', ropeGiving: 'high', primality: 'high', serviceGiving: 'high' },
    discoveryAnswers: { 'd-power-give': 'strong', 'r-lead': 'strong', 'd-rope': 'strong', 'r-rope-give': 'strong', 'd-primal': 'strong', 'r-primal-give': 'strong', 'd-service': 'strong', 'r-service-give': 'strong' },
    expectedPlausibleRoles: ['dominant', 'rigger', 'primal-hunter', 'service-dominant'],
    rationale: 'Family breadth should remain visible instead of collapsing every signal into one semantic cluster.',
    expectations: [expectRoleInTop('dominant', 12), expectRoleInTop('rigger', 12), expectRoleInTop('primal-hunter', 12)],
  },
]

export const calibrationPersonaById = Object.fromEntries(calibrationPersonas.map((persona) => [persona.id, persona])) as Record<string, CalibrationPersona>
